postgresHost: "localhost"
postgresPort: 5432
postgresUser: "postgres"
postgresPassword: "password"
postgresDB: "postgres"
kubeMQHost: "localhost"
kubeMQPort: 50000
usersChannel: "users"
group: ""
cacheChannel: "cache"
historyChannel: "history"
auditChannel: "audit"
logsChannel: "logs"
configChannel: "config"
notificationChannel: "notification"