# github.com/go-task/task

version: '2'

vars:
  BINARY_NAME: kubemq-elastic
  VERSION: v0.2.0

tasks:
  default:
    cmds:
      - go build -o "{{.BINARY_NAME}}.exe"
  run:
    cmds:
      - task: default
      - kubemq_elastic
  clean:
    cmds:
      - go clean
  docker:
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      -  go mod tidy
      -  go mod vendor
      -  docker build --build-arg VERSION={{.VERSION}} . -t kubemq/{{.BINARY_NAME}}:{{.VERSION}}
      -  docker tag kubemq/{{.BINARY_NAME}}:{{.VERSION}} kubemq/{{.BINARY_NAME}}:latest
  rundocker:
    cmds:
      - docker run -it --rm kubemq/{{.BINARY_NAME}}:{{.VERSION}}
  push:
    cmds:
      - docker push kubemq/{{.BINARY_NAME}}:{{.VERSION}}
      - docker push kubemq/{{.BINARY_NAME}}:latest
  release:
    cmds:
      - task: docker
      - task: push
